version: '3.8'
services:
  lavalink:
    container_name: lavamusic-lavalink
    image: ghcr.io/lavalink-devs/lavalink
    restart: on-failure
    environment:
      _JAVA_OPTIONS: -Xmx6G
      SERVER_PORT: 2333
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: 'Mahina@551238'
    volumes:
      # mount application.yml from the same directory or use environment variables
      - ./application.yml:/opt/Lavalink/application.yml
      # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
      - ./plugins/:/opt/Lavalink/plugins/
    expose:
      - 2333
    ports:
      - '2333:2333'
    networks:
      - lavalink
    healthcheck:
      test: 'curl -H "Authorization: Mahina@551238" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
networks:
  lavalink:
    name: lavalink
