services:
  lavalink:
    container_name: lavalink
    image: ghcr.io/lavalink-devs/lavalink
    restart: on-failure
    environment:
      - SERVER_PORT=2333
    volumes:
      - ./lavalink/application.yml:/opt/lavalink/application.yml
      - ./lavalink/plugins/:/opt/lavalink/plugins/
    networks:
      - lavalink-net
    expose:
      - 2333
    ports:
      - '2333:2333'
    healthcheck:
      test: 'curl -H "Authorization: Mahina@551238" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mahina:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mahina
    restart: always
    expose:
      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - lavalink
    env_file:
      - .env
    environment:
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE}
      PREFIX: ${PREFIX}
      OWNER_IDS: ${OWNER_ID}
      GUILD_ID: ${GUILD_ID}
      TOPGG: ${TOPGG}
      KEEP_ALIVE: ${KEEP_ALIVE}
      LOG_CHANNEL_ID: ${LOG_CHANNEL_ID}
      LOG_COMMANDS_ID: ${LOG_COMMANDS_ID}
      BOT_STATUS: ${BOT_STATUS}
      BOT_ACTIVITY_TYPE: ${BOT_ACTIVITY_TYPE}
      BOT_ACTIVITY: ${BOT_ACTIVITY}
      DATABASE_URL: ${DATABASE_URL}
      AUTO_NODE: ${AUTO_NODE}
      SEARCH_ENGINE: ${SEARCH_ENGINE}
      GENIUS_API: ${GENIUS_API}
      NODES: ${NODES}
    networks:
      - lavalink-net
networks:
  lavalink:
    name: lavalink-net
