FROM ghcr.io/lavalink-devs/lavalink:4.2.2

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates python3 unzip && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp && \
    curl -fsSL https://deno.land/install.sh | DENO_INSTALL=/usr/local sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER lavalink
