services:
  lavalink:
    container_name: lavamusic-lavalink
    image: ghcr.io/lavalink-devs/lavalink
    restart: on-failure
    environment:
      _JAVA_OPTIONS: -Xmx6G
      SERVER_PORT: 2333
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: 'Mahina@551238'
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    expose:
      - 2333
    ports:
      - '2333:2333'
    networks:
      - lavalink
    healthcheck:
      test: 'curl -H "Authorization: Mahina@551238" -s http://localhost:2333/version'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      - warp

  warp:
    image: caomingjun/warp
    restart: unless-stopped
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
    networks:
      - lavalink

networks:
  lavalink:
    driver: bridge
